{application,nms,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nms_app,[]}},
              {env,[]},
              {modules,[detector,gen_detector,http_detector,nms_app,
                        nms_monitor,nms_sup]}]}.
